<a href="https://colab.research.google.com/github/shabanakausar/shabanakausar/blob/main/Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
gamma = 0.85 #discount factor
alpha = 0.9  # learning rate

# define the states(Map each of the locations to numbers(states))
location_to_state = {'L1' : 0,
                     'L2' : 1,
                     'L3' : 2,
                     'L4' : 3,
                     'L5' : 4,
                     'L6' : 5,
                     'L7' : 6,
                     'L8' : 7,
                     'L9' : 8,
                     'L10': 9,
                     'L11': 10,
                     'L12': 11
    }
# define our action(actions here represents the transition to the next state:)
actions = [0,1,2,3,4,5,6,7,8,9,10,11]
#define the reward (get the reward table)
rewards = np.array(
            [[0,1,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,1,0,0,0],
            [0,0,0,0,0,1,0,0,0,0,0,0],
            [0,0,0,0,1,0,1,0,0,0,0,0],
            [0,0,0,1,0,0,0,1,0,0,0,0],
            [0,0,1,0,0,0,0,0,0,1,0,0],
            [0,0,0,1,0,0,0,0,0,0,0,0],
            [0,0,0,0,1,0,0,0,1,0,0,0],
            [0,1,0,0,0,0,0,1,0,0,1,0],
            [0,0,0,0,0,1,0,0,0,0,0,1],
            [0,0,0,0,0,0,0,0,1,0,0,1],
            [0,0,0,0,0,0,0,0,0,1,1,0]])

# Now,lets inverse mapping from the states back to original location indicators.
#since it will help identify locations using their current state
state_to_location = dict((state,location) for location,state in
location_to_state.items())

print(state_to_location)


{0: 'L1', 1: 'L2', 2: 'L3', 3: 'L4', 4: 'L5', 5: 'L6', 6: 'L7', 7: 'L8', 8: 'L9', 9: 'L10', 10: 'L11', 11: 'L12'}


In [ ]:
def get_optimal_route(starting_location,end_location):

    # lets make a copy of the reward matrix, we dont want to alter the origianl
    #table.

        rewards_copy = np.copy(rewards )
        print("rewards_copy is :","\n", rewards_copy)
        print()

        # create a random location for the golden key
        golden_key_location = np.random.randint(0,11)
        list_location_to_state = list(location_to_state.keys())
        end_location = list_location_to_state[golden_key_location]
        print(end_location)

        # Get the ending state corresponding to the ending location as given

        ending_state = location_to_state[end_location]
        print(ending_state)
        print()

        # Automatically set the priority of the
        # given ending state to the highest one
        rewards_copy[ending_state,ending_state]= 500
        print(rewards_copy)

        # Initialize Q -Values to zero
        Q = np.array(np.zeros([12,12]))

        # We will explore the environment for a while, by looping it through 1000
        #times.
        #We will then pick a state randomly from the set of states we defined above,
        # lets call "current_state".
        for i in range(1000):
            # Pick up a state randomly
            current_state = np.random.randint(0,12)

            # iterating through the rewards matrix,we get the states that are
            #directly reachable
            # from the randomly chosen current state and we will then assign those
            #states in a list
            # called "playable_actions".
            playable_actions = []
            for j in range (12):
                if rewards_copy[current_state,j]>0:
                    playable_actions.append(j)

                    # Pick an action randomly from the list of playable actions
                    #leading us to the next state
                    next_state = np.random.choice(playable_actions)
                    # Compute the temporal difference
                    # Note: The "action" here exactly refers to going to the "next
                    #state"
                    TD = rewards_copy[current_state,next_state ] + gamma*Q[next_state ,np.argmax(Q[next_state])]-Q[current_state,next_state]
                    # Update the Q-Value using the Bellman equation
                    Q[current_state,next_state]+= alpha*TD
        # Initialize the optimal route with the starting location
        route = [starting_location]
        # we at this juncture will have to set the next_location to the
        #starting_location, reason being that
        # we dont know what move the agent will be making at this moment
        next_location = starting_location

        # A "while loop will be goog for iteration in this case",
        # we don't know the exact number of iterations required to reach to the
        #final location.
        while(next_location != end_location):
            # pickup the starting state
            starting_state = location_to_state[starting_location]
            # pickup the highest Q-value pertaining to starting state
            next_state = np.argmax(Q[starting_state])
            # get the letters of the locations corresponding to the next state
            next_location = state_to_location[next_state]
            route.append(next_location)
            # Now we update the starting location for the next iteration
            starting_location = next_location

        return route

print(get_optimal_route("L12","L1"))



rewards_copy is : 
 [[0 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 1 0]]

L6
5

[[  0   1   0   0   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   1   0   0   0   0   0   0]
 [  0   0   0   0   1   0   1   0   0   0   0   0]
 [  0   0   0   1   0   0   0   1   0   0   0   0]
 [  0   0   1   0   0 500   0   0   0   1   0   0]
 [  0   0   0   1   0   0   0   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0   1   0   0   0]
 [  0   1   0   0   0   0   0   1   0   0   1   0]
 [  0   0   0   0   0   1   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   0   1   0   0   1]
 [  0   0   0   0   0   0   0   0   0   1   1   0]]
['L12', 'L10', 'L6']
